[package]
name = "ethdb"
version = "0.1.0"
authors = ["Annie Lai <ng8eke@163.com>"]
edition = "2018"
description = "Rust implementation of turbo-geth database format"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
arrayref = "0.3"
async-stream = "0.3"
async-trait = "0.1"
bytes = "1"
ethereum = { git = "https://github.com/rust-blockchain/ethereum" }
ethereum-types = "0.10"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
maplit = "1"
prost = "0.6"
rlp = "0.5"
rlp-derive = "0.1"
roaring = "0.6"
serde = "1"
serde_json = "1"
sha3 = "0.9"
tokio = { version = "1", features = ["rt"] }
tokio-stream = "0.1"
tonic = { version = "0.3", default-features = false, features = ["codegen", "prost", "transport"] }
tracing = "0.1"

[build-dependencies]
tonic-build = "0.3"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
tokio = { version = "1", features = ["full"] }
