[package]
name = "ethdb"
version = "0.1.0"
authors = ["Annie Lai <ng8eke@163.com>"]
edition = "2018"
description = "Rust implementation of turbo-geth database format"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
arrayref = "0.3"
async-stream = "0.3"
async-trait = "0.1"
auto_impl = "0.4"
bytes = "1"
educe = { version = "0.4", features = ["Debug"] }
ethereum = { git = "https://github.com/rust-blockchain/ethereum" }
ethereum-types = "0.10"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
maplit = "1"
mdbx-sys = { git = "https://github.com/vorot93/mdbx-rs" }
prost = "0.7"
rlp = "0.5"
rlp-derive = "0.1"
roaring = { git = "https://github.com/RoaringBitmap/roaring-rs" }
serde = "1"
serde_json = "1"
sha3 = "0.9"
tokio = { version = "1", features = ["rt"] }
tokio-stream = "0.1"
tonic = { version = "0.4", default-features = false, features = ["codegen", "prost", "transport"] }
tracing = "0.1"

[build-dependencies]
tonic-build = "0.4"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
